/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  barName?: string;
  introEn?: string;
  introTh?: string;
  addressEn?: string;
  addressTh?: string;
  openDaysEn?: string;
  openDaysTh?: string;
  openTimeEn?: string;
  openTimeTh?: string;
  mapUrl?: string;
  phone?: string;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
};

export type MenuSectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "menuSection";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type MenuItem = {
  _id: string;
  _type: "menuItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nameEn?: string;
  nameTh?: string;
  ingredientsEn?: string;
  ingredientsTh?: string;
  descriptionEn?: string;
  descriptionTh?: string;
  price?: number;
  section?: MenuSectionReference;
  spirits?: Array<
    | "gin"
    | "vodka"
    | "rum"
    | "tequilaMezcal"
    | "whiskeyBourbon"
    | "brandyCognac"
    | "liqueurAperitif"
    | "vermouthFortifiedWine"
    | "wineSparkling"
    | "beer"
    | "sakeSoju"
    | "nonAlcoholic"
  >;
  status?: "available" | "hidden" | "soldOut";
  sortOrder?: number;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type MenuSection = {
  _id: string;
  _type: "menuSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titleEn?: string;
  titleTh?: string;
  slug?: Slug;
  descriptionEn?: string;
  descriptionTh?: string;
  sortOrder?: number;
  isVisible?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | MenuSectionReference
  | SanityImageAssetReference
  | MenuItem
  | SanityImageCrop
  | SanityImageHotspot
  | MenuSection
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: menuSectionsQuery
// Query: *[_type == "menuSection"] | order(sortOrder asc){    _id,    titleEn,    titleTh,    "items": *[_type == "menuItem" && references(^._id)] | order(sortOrder asc){      _id,      nameEn,      price    }  }
export type MenuSectionsQueryResult = Array<{
  _id: string;
  titleEn: string | null;
  titleTh: string | null;
  items: Array<{
    _id: string;
    nameEn: string | null;
    price: number | null;
  }>;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "menuSection"] | order(sortOrder asc){\n    _id,\n    titleEn,\n    titleTh,\n    "items": *[_type == "menuItem" && references(^._id)] | order(sortOrder asc){\n      _id,\n      nameEn,\n      price\n    }\n  }\n': MenuSectionsQueryResult;
  }
}
